<div id="actor-signin-page">
	<div id="main_content" class="container-fluid">
		<div class="row">
			<div class="col-sm-6 col-sm-offset-3">
				<h1 class="bam-title"><span class="extra-large">B</span>rimstone <span class="extra-large">A</span>ctor <span class="extra-large">M</span>anagement</h1>
				<br/>
				<p>Welcome to the Brimstone Actor Management System. If you are an active actor at Brimstone Haunt please sign in below. If you are interested in becoming an actor at Brimstone Haunt, you can <a href="#">fill out an application</a>.</p>
				<form action="" onsubmit="alert('Hello'); return false;">
					<input class="form-control" type="text" placeholder="Email" />
					<input class="form-control" type="password" placeholder="Password" />
					<input class="btn btn-primary btn-block" type="submit" value="SIGN IN" />
					<center><button class="btn btn-link" onclick="return false;">Forgot Password</button></center>
				</form>
			</div>
		</div>
	</div>
</div>
