<div id="footer" class="container-fluid">
	<div class="row">
		<div class="col-sm-12">
			<center>
				<span>&copy; 2017 Brimstone Haunt LLC. | <a href="mailto:contact@BrimstoneHaunt.com">contact@BrimstoneHaunt.com</a></span>
			</center>
		</div>
	</div>
</div>
<div id="my-modal-container">
	<div id="my-empty-modal" class="modal fade hidden" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h3 class="modal-title"></h3>
				</div>
				<div class="modal-body"></div>
				<div class="modal-footer"></div>
			</div>
		</div>
	</div>
</div>