<nav id="main_nav" class="navbar navbar-default navbar-fixed-top tall">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?php echo $base_url; ?>"><img src="view/img/BHH_Logo_Text.png"></a>
		</div>
		<div class="collapse navbar-collapse" id="main-nav">
			<ul class="nav navbar-nav">
				<li><a href="javascript:void(0)" onclick="pages['home'].scrollTo('#attractions');" title="Attractions">Attractions</a></li>
				<li><a href="javascript:void(0)" onclick="pages['home'].scrollTo('#tickets');"title="Tickets">Tickets</a></li>
				<li><a href="javascript:void(0)" onclick="pages['home'].scrollTo('#directions');" title="Directions">Directions</a></li>
				<li><a href="javascript:void(0)" onclick="pages['home'].scrollTo('#faq');" title="FAQ">FAQ</a></li>
				<li><a href="javascript:void(0)" onclick="pages['home'].scrollTo('#about');" title="About Us">About Us</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li><a href="http://actors.brimstonehaunt.com/apply" target="_blank" title="NOW HIRING">NOW HIRING</a></li>
			</ul>
		</div>
	</div>
</nav>