<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Facebook Preview Stuff -->
    <meta property="og:image" content="<?php echo $base_url; ?>/view/img/BHH_Logo.jpg" />
    <meta property="og:title" content="Brimstone Haunted Hayride" />
    <meta property="og:description" content="Brimstone Haunt was founded on the heels of Springboro Haunted Hayride's closing. The producers of the Ohio Renaissance Festival along with the core management team from the old Springboro Haunted Hayride came together to keep the fall tradition alive." />
    
    <!-- favicon -->
    <link rel="apple-touch-icon" sizes="57x57" href="/mediashare/apple-icon-57x57.png">
	<link rel="apple-touch-icon" sizes="60x60" href="/mediashare/apple-icon-60x60.png">
	<link rel="apple-touch-icon" sizes="72x72" href="/mediashare/apple-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="76x76" href="/mediashare/apple-icon-76x76.png">
	<link rel="apple-touch-icon" sizes="114x114" href="/mediashare/apple-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="120x120" href="/mediashare/apple-icon-120x120.png">
	<link rel="apple-touch-icon" sizes="144x144" href="/mediashare/apple-icon-144x144.png">
	<link rel="apple-touch-icon" sizes="152x152" href="/mediashare/apple-icon-152x152.png">
	<link rel="apple-touch-icon" sizes="180x180" href="/mediashare/apple-icon-180x180.png">
	<link rel="icon" type="image/png" sizes="192x192"  href="/mediashare/android-icon-192x192.png">
	<link rel="icon" type="image/png" sizes="32x32" href="/mediashare/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="96x96" href="/mediashare/favicon-96x96.png">
	<link rel="icon" type="image/png" sizes="16x16" href="/mediashare/favicon-16x16.png">
	<link rel="manifest" href="/mediashare/manifest.json">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-TileImage" content="/mediashare/ms-icon-144x144.png">
	<meta name="theme-color" content="#ffffff">
    
	<title>Brimstone Haunt | <?php echo $pageTitles[$page]; ?></title>
	
	<!-- JQuery -->
	<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
	
	<!-- Bootstrap -->
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<!-- Swiper -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/css/swiper.min.css">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/js/swiper.jquery.min.js"></script>
	
	<!-- Analytics -->
	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-97987615-1', 'auto');
		ga('send', 'pageview');
	</script>
	
	<!-- custom -->
	<link href='//fonts.googleapis.com/css?family=Creepster' rel='stylesheet'>
	<link href="view/css/main.css" rel="stylesheet">
	<script>
		var pageName = "<?php echo $page; ?>";
		var code_version  = "<?php echo $code_version; ?>";
	</script>
	<script src="view/js/main.js"></script>
	<script src="view/js/<?php echo $page; ?>.js"></script>
</head>