<html>
	<?php require_once("head.phtml"); ?>
	<body>
		<?php require_once("simple_header.phtml"); ?>
		<div id="news-page">
			<div id="main_content" class="container-fluid">
				<div class="row">
					<div class="col-xs-12"><h2>2017 News</h2></div>
					<div class="col-xs-12">
						<ul>
							<li><a href="<?php echo $base_url; ?>/mediashare/pdf/media_release_08242017.pdf" target="_blank">Media Release</a></li>
							<li><a href="https://www.thescarefactor.com/haunt-blog/2017-top-ohio-haunted-houses-list/" target="_blank">#2 In Ohio on The Scare Factor's Top 10 Must See List</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<?php require_once("footer.phtml"); ?>
	</body>
</html>