<html>
	<?php require_once("head.phtml"); ?>
	<body>
		<?php require_once("simple_header.phtml"); ?>
		<div id="photos-page">
			<div id="main_content" class="container-fluid">
				<!-- <div class="row">
					<div class="col-xs-12"><h2>Videos</h2></div>
					<div class="img-container vid col-lg-3 col-md-4 col-sm-6">
						<a href="media/2017_teaser.mp4" target="_blank"><img src="media/hayride_placeholder.jpg" /></a>
					</div>
				</div> -->
				<div class="row">
					<div class="col-xs-12"><h2>Photos</h2></div>
					<div class="img-container col-lg-3 col-md-4 col-sm-6">
						<a href="media/hayride.jpeg" target="_blank"><img src="media/hayride.jpeg" /></a>
					</div>
					<!-- <div class="img-container col-lg-3 col-md-4 col-sm-6">
						<a href="media/forest_placeholder.jpg" target="_blank"><img src="media/forest_placeholder.jpg" /></a>
					</div> -->
					<div class="img-container col-lg-3 col-md-4 col-sm-6">
						<a href="media/black_forest.jpeg" target="_blank"><img src="media/black_forest.jpeg" /></a>
					</div>
					<!-- <div class="img-container col-lg-3 col-md-4 col-sm-6">
						<a href="media/hayride_placeholder.jpg" target="_blank"><img src="media/hayride_placeholder.jpg" /></a>
					</div> -->
				</div>
			</div>
		</div>
		<?php require_once("footer.phtml"); ?>
	</body>
</html>