<nav id="main_nav" class="navbar navbar-default navbar-fixed-top tall">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?php echo $base_url; ?>"><img src="mediashare/img/logos/brimstone_haunt_flat_color.png"></a>
		</div>
		<div class="collapse navbar-collapse" id="main-nav">
			<ul class="nav navbar-nav navbar-right">
				<li>
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
						Links <span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<!-- <li><a href="http://blog.brimstonehaunt.com" target="_blank">Brimstone Blog</a> -->
						<li><a href="<?php echo $base_url; ?>/photos">Photos and Videos</a></li>
						<li><a href="<?php echo $base_url; ?>/team">The Team</a></li>
						<li><a href="<?php echo $base_url; ?>/sponsors">Our Sponsors</a></li>
						<li><a href="<?php echo $base_url; ?>/news">News</a></li>
						<li role="separator" class="divider"></li>
						<!-- <li><a href="http://www.renparkusa.com" target="_blank">Renaissance Park</a></li> -->
						<li><a href="http://www.renfestival.com" target="_blank">Ohio Renaissance Festival</a></li>
						<li><a href="http://www.celticfestohio.com" target="_blank">Celtic Fest Ohio</a></li>
						<li><a href="http://www.1572roadhousebarbq.com" target="_blank">1572 Roadhouse BarB-Q</a></li>
						<li><a href="http://www.renparkhenge.com" target="_blank">Sun Henge</a></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</nav>