<html>
	<?php require_once("head.phtml"); ?>
	<body>
		<?php require_once("header.phtml"); ?>
		<div id="sponsor-page">
			<div id="main_content" class="container-fluid">
				<div class="row">
					<div id="sponsors" class="col-md-6">
						<h2>Our Sponsors</h2>
						<div class="row">
							<div class="logo-container col-md-4 col-xs-6">
								<a href="http://www.jdequipment.com" target="_blank"><img src="media/sponsors/jd_equipment_logo.png" /></a>
							</div>
							<div class="logo-container col-md-4 col-xs-6">
								<a href="http://www.ohiohauntedhouses.com" target="_blank"><img src="media/sponsors/ohio_hh_logo.jpeg" /></a>
							</div>
						</div>
					</div>
					<div id="partners" class="col-md-6">
						<h2>Our Partners</h2>
						<div class="row">
							<div class="logo-container col-md-4 col-xs-6">
								<a href="http://www.renfestival.com" target="_blank"><img src="media/sponsors/renfest_logo.png" /></a>
							</div>
							<div class="logo-container col-md-4 col-xs-6">
								<a href="http://www.celticfestohio.com" target="_blank"><img src="media/sponsors/celticfest_logo.png" /></a>
							</div>
							<div class="logo-container col-md-4 col-xs-6">
								<a href="http://www.1572roadhousebarbq.com" target="_blank"><img src="media/sponsors/bbq_logo.png" /></a>
							</div>
							<div class="logo-container col-md-4 col-xs-6">
								<a href="http://www.renparkhenge.com" target="_blank"><img src="media/sponsors/henge_logo.png" /></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<?php require_once("footer.phtml"); ?>
	</body>
</html>