<html>
	<?php require_once("head.phtml"); ?>
	<body>
		<?php require_once("simple_header.phtml"); ?>
		<div id="team-page">
			<div id="main_content" class="container-fluid">
				<div class="row">
					<div class="col-md-6 col-md-offset-3">
						<p>Without our incredible team, Brimstone Haunted Hayride would still be just a corn field. There is a large group of people that play a role in making our haunt a success and we cannot thank and recognize everyone enough. Below are some of the core people from our team that put their heart and soul into this place each and every year.</p>
						<p>Anyone interested in joining our team, please check out our <a href="http://actors.brimstonehaunt.com/jobs" target="_blank">current job listings</a>.</p>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-12"><h2>Management</h2></div>
					<div class="team-member col-lg-2 col-md-3 col-sm-4 col-xs-6">
						<div class="row">
							<div class="col-xs-12">
								<img src="" />
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12">
								<span>Brandon Moore</span>
							</div>
							<div class="col-xs-12">
								<span>CEO</span>
							</div>
						</div>
					</div>
					<div class="team-member col-lg-2 col-md-3 col-sm-4 col-xs-6">
						<div class="row">
							<div class="col-xs-12">
								<img src="" />
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12">
								<span>Philip Flynn</span>
							</div>
							<div class="col-xs-12">
								<span>CTO</span>
							</div>
						</div>
					</div>
					<div class="team-member col-lg-2 col-md-3 col-sm-4 col-xs-6">
						<div class="row">
							<div class="col-xs-12">
								<img src="" />
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12">
								<span>Marc Maeder</span>
							</div>
							<div class="col-xs-12">
								<span>Staffing Director</span>
							</div>
						</div>
					</div>
					<div class="team-member col-lg-2 col-md-3 col-sm-4 col-xs-6">
						<div class="row">
							<div class="col-xs-12">
								<img src="" />
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12">
								<span>Lynzee Flynn</span>
							</div>
							<div class="col-xs-12">
								<span>Talent Manager</span>
							</div>
						</div>
					</div>
				</div>
				<!-- <div class="row">
					<div class="full-team col-xs-12">
						<img src="" />
						<span>The 2017 Management Team</span>
					</div>
				</div> -->
				<div class="row">
					<div class="col-xs-12"><h2>Consultants</h2></div>
					<div class="team-member col-lg-2 col-md-3 col-sm-4 col-xs-6">
						<div class="row">
							<div class="col-xs-12">
								<img src="" />
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12">
								<span>Hank Henry</span>
							</div>
							<div class="col-xs-12">
								<span>Consulting Scene Designer</span>
							</div>
						</div>
					</div>
					<div class="team-member col-lg-2 col-md-3 col-sm-4 col-xs-6">
						<div class="row">
							<div class="col-xs-12">
								<img src="" />
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12">
								<span>Christine</span>
							</div>
							<div class="col-xs-12">
								<span>Consulting Operations Manager</span>
							</div>
						</div>
					</div>
				</div>
				<!-- <div class="row">
					<div class="full-team col-xs-12">
						<img src="" />
						<span>The 2017 Consulting Team</span>
					</div>
				</div> -->
				<div class="row">
					<div class="col-xs-12"><h2>Builders</h2></div>
					<div class="team-member col-lg-2 col-md-3 col-sm-4 col-xs-6">
						<div class="row">
							<div class="col-xs-12">
								<img src="" />
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12">
								<span>Jeff Sesslar</span>
							</div>
							<div class="col-xs-12">
								<span>Construction</span>
							</div>
						</div>
					</div>
					<div class="team-member col-lg-2 col-md-3 col-sm-4 col-xs-6">
						<div class="row">
							<div class="col-xs-12">
								<img src="" />
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12">
								<span>Rina</span>
							</div>
							<div class="col-xs-12">
								<span>Construction</span>
							</div>
						</div>
					</div>
				</div>
				<!-- <div class="row">
					<div class="full-team col-xs-12">
						<img src="" />
						<span>The 2017 Build Team</span>
					</div>
				</div> -->
				<div class="row">
					<div class="col-xs-12"><h2>Actors</h2></div>
					<div class="team-member col-lg-2 col-md-3 col-sm-4 col-xs-6">
						<div class="row">
							<div class="col-xs-12">
								<img src="" />
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12">
								<span>Shaun Bolen</span>
							</div>
							<div class="col-xs-12">
								<span>The Skinner</span>
							</div>
						</div>
					</div>
					<div class="team-member col-lg-2 col-md-3 col-sm-4 col-xs-6">
						<div class="row">
							<div class="col-xs-12">
								<img src="" />
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12">
								<span>Jon Moran</span>
							</div>
							<div class="col-xs-12">
								<span>The Boogeyman</span>
							</div>
						</div>
					</div>
				</div>
				<!-- <div class="row">
					<div class="full-team col-xs-12">
						<img src="" />
						<span>The 2017 Acting Team</span>
					</div>
				</div> -->
			</div>
		</div>
		<?php require_once("footer.phtml"); ?>
	</body>
</html>